package student.management.estudent.domain.activities;

import lombok.Data;

@Data
public class Activity {
    private String title;
    private String description;
    private String detail;
    private String date;

    // Constructor
    public Activity(){

    }

    public Activity(String title, String description, String detail, String date) {
        this.title = title;
        this.description = description;
        this.detail = detail;
        this.date = date;
    }

    // Getters and Setters
    //Generated by lombok
}
